# ELF Makefile

CC=gcc

0-hreadelf: 0_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 0_main.c -o 0-hreadelf
	cp 0-hreadelf test
	touch 0_main.c

1-hreadelf: 1_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 1_main.c -o 1-hreadelf
	cp 1-hreadelf test
	touch 1_main.c

2-hreadelf: 2_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 2_main.c -o 2-hreadelf
	cp 2-hreadelf test
	touch 2_main.c

100-hreadelf: 100_main.c
	$(CC) -Wall -Werror -Wextra -pedantic 100_main.c -o 100-hreadelf
	cp 100-hreadelf test
	touch 100_main.c
